services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    stdin_open: true
    tty: true
    environment:
      - INPUT_PATH=/app/images/
      - SERVER_PORT=:8080
    volumes:
      - ./images:/app/images
    restart: on-failure

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - SERVER_ADDR=server:8080
    depends_on:
      - server
    scale: 3
    restart: on-failure